/*========== 自定义专题图-新增模板 ==========*/
/*1.基本信息*/
DROP VIEW IF EXISTS "BB_SESGIS_CUSTOM_THEMATICS";
CREATE VIEW "BB_SESGIS_CUSTOM_THEMATICS" AS (SELECT * FROM SESGIS_CUSTOM_THEMATICS WHERE ID IN (${CUSTOM_THEMATIC_IDS}));

/*模块配置*/
DROP VIEW IF EXISTS "BB_SESGIS_MODULE_CONFIGS";
CREATE VIEW "BB_SESGIS_MODULE_CONFIGS" AS (SELECT * FROM SESGIS_MODULE_CONFIGS WHERE ID IN (SELECT GET_MODULE FROM SESGIS_CUSTOM_THEMATICS WHERE ID IN (${CUSTOM_THEMATIC_IDS})));

/*2.图层属性服务获取*/
DROP VIEW IF EXISTS "BB_SESGIS_LAYER_PROPERTIES";
CREATE VIEW "BB_SESGIS_LAYER_PROPERTIES" AS (SELECT * FROM SESGIS_LAYER_PROPERTIES WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*3.点击列表数据展示*/
DROP VIEW IF EXISTS "BB_SESGIS_LIST_DATA_SHOWS";
CREATE VIEW "BB_SESGIS_LIST_DATA_SHOWS" AS (SELECT * FROM SESGIS_LIST_DATA_SHOWS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*4.点击工具栏按钮设置*/
DROP VIEW IF EXISTS "BB_SESGIS_CLICK_TOOLS";
CREATE VIEW "BB_SESGIS_CLICK_TOOLS" AS (SELECT * FROM SESGIS_CLICK_TOOLS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*5.符号配置*/
DROP VIEW IF EXISTS "BB_SESGIS_SYMBOL_RULESS";
CREATE VIEW "BB_SESGIS_SYMBOL_RULESS" AS (SELECT * FROM SESGIS_SYMBOL_RULESS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*6.扩展功能按钮*/
DROP VIEW IF EXISTS "BB_SESGIS_EXTENDED_BUTTONS";
CREATE VIEW "BB_SESGIS_EXTENDED_BUTTONS" AS (SELECT * FROM SESGIS_EXTENDED_BUTTONS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*7.其他扩展配置*/
DROP VIEW IF EXISTS "BB_SESGIS_CUSTOM_EXTENDS";
CREATE VIEW "BB_SESGIS_CUSTOM_EXTENDS" AS (SELECT * FROM SESGIS_CUSTOM_EXTENDS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*8.专题图插件*/
DROP VIEW IF EXISTS "BB_SESGIS_CUSTOM_PLUGINS";
CREATE VIEW "BB_SESGIS_CUSTOM_PLUGINS" AS (SELECT * FROM SESGIS_CUSTOM_PLUGINS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);
/*专题图插件表(专题图插件配置 SESGIS_CUS_LAYER_PLUGINS.PLUGIN_ID)*/
DROP VIEW IF EXISTS "BB_SESGIS_SCREEN_PLUGINSS";
DROP VIEW IF EXISTS "BB_SESGIS_PLUGINS_DETAILSS";
CREATE VIEW "BB_SESGIS_SCREEN_PLUGINSS" AS (SELECT * FROM SESGIS_SCREEN_PLUGINSS WHERE ID IN (SELECT PLUGIN_ID FROM SESGIS_CUSTOM_PLUGINS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1) AND VALID = 1);
CREATE VIEW "BB_SESGIS_PLUGINS_DETAILSS" AS (SELECT * FROM SESGIS_PLUGINS_DETAILSS WHERE PLUGIN_ID IN (SELECT PLUGIN_ID FROM SESGIS_CUSTOM_PLUGINS WHERE BASIC_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1) AND VALID = 1);

/*9.自定义专题图模板-自定义专题图引导*/
DROP VIEW IF EXISTS "BB_SESGISCONFIG_CUSTOM_GUIDES";
CREATE VIEW "BB_SESGISCONFIG_CUSTOM_GUIDES" AS (SELECT * FROM SESGISCONFIG_CUSTOM_GUIDES WHERE BASE_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*10.自定义专题图模板-常驻扩展面板*/
DROP VIEW IF EXISTS "BB_SESGISCONFIG_EXPAN_PANELS";
CREATE VIEW "BB_SESGISCONFIG_EXPAN_PANELS" AS (SELECT * FROM SESGISCONFIG_EXPAN_PANELS WHERE BASE_INFO_ID IN (${CUSTOM_THEMATIC_IDS}) AND VALID = 1);

/*========== 主题配置-新增模板 ==========*/
/*1.主题信息*/
DROP VIEW IF EXISTS "CC_SESGIS_THEME_CONFIGS";
CREATE VIEW "CC_SESGIS_THEME_CONFIGS" AS (SELECT * FROM SESGIS_THEME_CONFIGS WHERE ID IN (${THEME_CONFIG_IDS}));

/*2.主图层自定义专题图*/
DROP VIEW IF EXISTS "CC_SES_MAIN_LAYER_CUSS";
CREATE VIEW "CC_SES_MAIN_LAYER_CUSS" AS (SELECT * FROM SES_MAIN_LAYER_CUSS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1);

/*3.专题底图*/
DROP VIEW IF EXISTS "CC_SES_BASE_MAP_LAYERSS";
CREATE VIEW "CC_SES_BASE_MAP_LAYERSS" AS (SELECT * FROM SES_BASE_MAP_LAYERSS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1);

/*4.全局插件*/
UPDATE SESGIS_CONFIG_PLUGIS SET VALID = 0 WHERE VALID = 1 AND PLUGINS IN (SELECT ID FROM SESGIS_CONFIG_PLUGINSS WHERE VALID = 0);
DROP VIEW IF EXISTS "CC_SESGIS_CONFIG_PLUGIS";
CREATE VIEW "CC_SESGIS_CONFIG_PLUGIS" AS (SELECT * FROM SESGIS_CONFIG_PLUGIS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1);
/*全局插件（全局插件配置 SESGIS_CONFIG_PLUGIS.PLUGINS）*/

/*5.全局插件配置*/
UPDATE SESGIS_THEME_PLUGINSS SET VALID = 0 WHERE VALID = 1 AND PLUGIN_ID IN (SELECT ID FROM SESGIS_CONFIG_PLUGINSS WHERE VALID = 0);
DROP VIEW IF EXISTS "CC_SESGIS_THEME_PLUGINSS";
CREATE VIEW "CC_SESGIS_THEME_PLUGINSS" AS (SELECT * FROM SESGIS_THEME_PLUGINSS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1);
/*全局插件（全局插件配置 SESGIS_THEME_PLUGINSS.PLUGIN_ID）*/
DROP VIEW IF EXISTS "CC_SESGIS_CONFIG_PLUGINSS";
DROP VIEW IF EXISTS "CC_SESGIS_CONFIG_PLUG_CONFS";
CREATE VIEW "CC_SESGIS_CONFIG_PLUGINSS" AS (SELECT * FROM SESGIS_CONFIG_PLUGINSS WHERE ID IN (SELECT PLUGIN_ID FROM SESGIS_THEME_PLUGINSS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1 UNION SELECT PLUGINS FROM SESGIS_CONFIG_PLUGIS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1) AND VALID = 1);
CREATE VIEW "CC_SESGIS_CONFIG_PLUG_CONFS" AS (SELECT * FROM SESGIS_CONFIG_PLUG_CONFS WHERE PLUGIN_ID IN (SELECT PLUGIN_ID FROM SESGIS_THEME_PLUGINSS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1 UNION SELECT PLUGINS FROM SESGIS_CONFIG_PLUGIS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1) AND VALID = 1);

/*6.专题图插件配置*/
DROP VIEW IF EXISTS "CC_SESGIS_CUS_LAYER_PLUGINS";
CREATE VIEW "CC_SESGIS_CUS_LAYER_PLUGINS" AS (SELECT * FROM SESGIS_CUS_LAYER_PLUGINS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1);

/*7.常驻扩展面板排序*/
DROP VIEW IF EXISTS "CC_SESGISCONFIG_EXP_PANELS";
CREATE VIEW "CC_SESGISCONFIG_EXP_PANELS" AS (SELECT * FROM SESGISCONFIG_EXP_PANELS WHERE THEME_ID IN (${THEME_CONFIG_IDS}) AND VALID = 1);